### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [alexbr9007/The_Complete_JS_Course_Udemy#1]
.

**Comment by a-bautista** [comment]
Hello Arthur,

Thank you very much for have had the time to look into of my repos and for
your invitation to collaborate in one of your Open Source projects. I
checked your deployed app http://groceristar.herokuapp.com/ and took a look
at the current repo and noticed the technologies that I am familiar such as
JS, moreover, I checked the ChickenKyiv repo and noticed that the main
technology that you use was React - a technology I am trying to learn and
practice. I am interested in participating in this Open Source project and
I would like to know what are your goals about this project or what would
you expect from my side in order to participate in this project.

-Alex
